create table public.reminder_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  email text not null,
  reminder_count smallint not null default 1
    check (reminder_count between 1 and 3),
  reminder_times text[] not null default array['09:00']::text[]
    check (cardinality(reminder_times) between 1 and 3),
  timezone text not null default 'Asia/Shanghai'
    check (timezone = 'Asia/Shanghai'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (cardinality(reminder_times) = reminder_count)
);

alter table public.reminder_preferences enable row level security;

create policy "Users can read their own reminder preferences"
on public.reminder_preferences
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own reminder preferences"
on public.reminder_preferences
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own reminder preferences"
on public.reminder_preferences
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own reminder preferences"
on public.reminder_preferences
for delete
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete
on public.reminder_preferences
to authenticated;

grant select, insert, update, delete
on public.reminder_preferences
to service_role;

create table public.reminder_delivery_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_date date not null,
  reminder_time text not null,
  status text not null
    check (status in ('processing', 'sent', 'skipped', 'failed')),
  task_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (user_id, reminder_date, reminder_time)
);

alter table public.reminder_delivery_log enable row level security;

comment on table public.reminder_delivery_log is
  'Server-only idempotency and delivery audit log for work reminder emails.';

grant select, insert, update
on public.reminder_delivery_log
to service_role;

grant usage, select
on sequence public.reminder_delivery_log_id_seq
to service_role;
